config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :users

  get '/users/:id/matches' => 'users#matches', :as => :matches
  get '/users/:id/all' => 'users#all', :as => :all

  get '/chats/:user_id/new' => 'chats#new', :as => :new_chat
  post '/chats/:id' => 'chats#create'
  get 'chats/:id' => 'chats#show', :as => :chat
  get '/chats/:id/match' => 'chats#match', :as => :match

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  firstname       :string(255)
#  lastname        :string(255)
#  gender          :string(255)
#  preference      :string(255)
#  birthday        :date
#  suburb          :string(255)
#  cuisines        :string(255)
#  hobbies         :string(255)
#  about           :text
#  image           :text
#  astro_id        :integer
#  lunar_id        :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  zodiac_reader :birthday
  has_secure_password
  belongs_to :astro
  belongs_to :lunar
  has_many :chats
  has_many :messages

  validates :email, :presence => true, :length => { :minimum => 5 }, :uniqueness => true
  validates :password_digest, :presence => true
  validates :firstname, :presence => true
  validates :lastname, :presence => true
  validates :birthday, :presence => true
  validates :image, :presence => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :check_if_logged_in, :except => [:new, :create]

  def index
    @users1 = Chat.where(:user1_id => @current_user.id)
    @users2 = Chat.where(:user2_id => @current_user.id)
    @users_all = User.all[0..15]
    fortune
  end

  def create
    @user = User.new user_params
    @user.astro_id = zodiac
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @user = User.find params[:id]
    @chat = Chat.find_by(:user1_id => [@current_user.id, @user.id],
                         :user2_id => [@current_user.id, @user.id])
  end

  def update
    @user = User.find params[:id]
    @user.astro_id = zodiac
    @user.update user_params
    redirect_to root_path
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to root_path
  end

  def matches
    @users = compatibility
    @users_all = User.all[0..15]
  end

  def all
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname, :gender, :preference, :birthday, :age, :suburb, :cuisines, :hobbies, :about, :image, :astro_id, :lunar_id)
  end

  def check_if_logged_in
    redirect_to(login_path) if @current_user.nil?
  end

  def compatibility
    preference = @current_user.preference
    x = @current_user.astro_id
    y = x + 4; y -= 12 if y > 12
    z = x + 8; z -= 12 if z > 12
    User.where(:astro_id => [y, z], :gender => preference)
  end

  def zodiac
    Astro.find_by(:sign => @user.zodiac_sign).id if @user.birthday.present?
  end

  def fortune
    url = "http://pipes.yahoo.com/pipes/pipe.run?_id=56d38d9e17c3f5969e443e2dc13e5b61&_render=json&sign=#{@current_user.zodiac_sign}&url=http%3A%2F%2Ffeeds.astrology.com%2Fdailyoverview"
    response = HTTParty.get(url)
    @current_user.astro.dailyfeed = response['value']['items'].first['description'].split(/<|>/)[2]
    @astro_image = 'http://www.compatible-astrology.com/image-files/' + @current_user.astro.sign.downcase + '1.gif'
  end

end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li class='notice'><%= msg %></li>
    <% end %>
  </ol>
<% end %>


<%= form_for @user do |f| %>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email, :autofocus => true %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation %>
  </p>
  <hr>
  <p>
    <%= f.label :firstname, 'First Name' %>
    <%= f.text_field :firstname %>
  </p>

  <p>
    <%= f.label :lastname, 'Surname' %>
    <%= f.text_field :lastname %>
  </p>
  <hr>
  <p>
    <%= f.label :gender %>
    <%= f.select(:gender, ['Male', 'Female']) %>
  </p>

  <p>
    <%= f.label :preference %>
    <%= f.select(:preference, ['Male', 'Female']) %>
  </p>

  <p>
    <%= f.label :birthday, 'Date of Birth' %>
    <%= f.date_field :birthday %>
  </p>

  <p>
    <%= f.label :suburb %>
    <%= f.text_field :suburb %>
  </p>
  <hr>
  <p>
    <%= f.label :cuisines, 'Favorite Cuisine' %>
    <%= f.text_field :cuisines%>
  </p>

  <p>
    <%= f.label :hobbies %>
    <%= f.text_field :hobbies %>
  </p>

  <p>
    <%= f.label :about %>
    <%= f.text_field :about %>
  </p>

  <p>
    <%= f.label :image, 'Image URL' %>
    <%= f.url_field :image %>
  </p>
  <hr>
  <%= f.submit %>
<% end %>

app/views/users/all.html.erb
<h2>All Candidates</h2>

<% @users.each do |user| %>
  <div class='box'>
    <h3><%= link_to(user.firstname, user_path(user)) %></h3>
    <%= image_tag(user.image, :class => "thumb") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h2>Home</h2>

<div class='box'>
  <h3>Today's Horoscope</h3>
  <%= image_tag(@astro_image, :class => 'sign') %>
  <p><%= @current_user.astro.dailyfeed %></p>
</div>

<div class='box'>
    <h3><%= link_to('View Matches', matches_path(@current_user)) %></h3>
    <% @users_all.each do |user| %>
      <%= image_tag(user.image, :class => "px48") %>
    <% end %>
</div>

<% @users1.each do |user| %>
  <div class='box'>
    <h3><%= link_to(User.find(user.user2_id).firstname, user_path(user.user2_id)) %></h3>
    <%= image_tag(User.find(user.user2_id).image, :class => "thumb") %>
    <%= link_to('Continue Chat', chat_path(user), :class => 'match') %>
  </div>
<% end %>

<% @users2.each do |user| %>
  <div class='box'>
    <h3><%= link_to(User.find(user.user1_id).firstname, user_path(user.user1_id)) %></h3>
    <%= image_tag(User.find(user.user1_id).image, :class => "thumb") %>
    <%= link_to('Continue Chat', chat_path(user), :class => 'match') %>
  </div>
<% end %>

app/views/users/matches.html.erb
<h2>Compatible Matches</h2>

<% @users.each do |user| %>
  <div class='box'>
    <h3><%= link_to(user.firstname, user_path(user)) %></h3>
    <%= image_tag(user.image, :class => "thumb") %>
  </div>
<% end %>

<div class='box'>
    <h3><%= link_to('View All', all_path) %></h3>
    <% @users_all.each do |user| %>
      <%= image_tag(user.image, :class => "px48") %>
    <% end %>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h2><%= @user.firstname %>'s Profile</h2>

<div class='box'>
  <h3><%= @user.firstname %></h3>
  <p>Gender: <%= @user.gender %></p>
  <p>Favorite Cuisines: <%= @user.cuisines %></p>
  <p>Hobbies: <%= @user.hobbies %></p>
  <p>About: <%= @user.about %></p>

  <% if @current_user == @user %>
  <% elsif @chat.present? %>
    <p><%= link_to('Continue Chat', chat_path(@chat), :class => 'match') %></p>
  <% else %>
    <p><%= link_to('Start Chat', new_chat_path(@user.id), :class => 'match') %></p>
  <% end %>
</div>

<%= image_tag(@user.image, :class => 'bigbox') %>