config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :users

  get '/users/:id/matches' => 'users#matches', :as => :matches
  get '/users/:id/all' => 'users#all', :as => :all

  get '/chats/:user_id/new' => 'chats#new', :as => :new_chat
  post '/chats/:id' => 'chats#create'
  get 'chats/:id' => 'chats#show', :as => :chat
  get '/chats/:id/match' => 'chats#match', :as => :match

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id         :integer          not null, primary key
#  user1_id   :integer
#  user2_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Chat < ActiveRecord::Base
  belongs_to :user
  has_many :message
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def new
    chat = Chat.new
    chat.user1_id = @current_user.id
    chat.user2_id = params[:user_id]
    chat.save
    Message.create(:chat_id => chat.id, :user_id => @current_user.id, :message => "has started a conversation.")
    redirect_to chat_path(chat)
  end

  def create
    chat = Chat.find params[:id]
    Message.create(:chat_id => params[:id], :user_id => @current_user.id, :message => params[:message])
    redirect_to chat_path(chat)
  end

  def show
    @chat = Chat.find params[:id]
    @user1 = (User.find_by :id => @chat.user1_id)
    @user2 = (User.find_by :id => @chat.user2_id)
    @messages = Message.where(:chat_id => @chat.id)
  end

  def match
    @chat = Chat.find params[:id]
    @user1 = (User.find_by :id => @chat.user1_id)
    @user2 = (User.find_by :id => @chat.user2_id)
    places
  end

  private

  def places
    @suggestions = ['Suggested Restaurants', 'Suggested Cafes', 'Suggested Bars'] # Types of suggestions
    @restaurants = {} # Make an empty arraay
      ['food&keyword=' + @current_user.cuisines, 'cafe', 'bar'].map do |type| # For each type of suggestion, we put it through the Google Place API
        url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=3000&types=" + type + "&key=AIzaSyDzMn29qnBUFN4FUuepeyzhSbQo1J9lkvo"
        response = HTTParty.get(url) # The Data received
        if response['results'].present? # Just in case the API stops working again
          [0, 1, 2].map do |x|
            y = rand(x * 3..x * 3 + 2) # Acquiring a random place so we don't receive the same result
            @restaurants[response['results'][y]['name']] = response['results'][y]['vicinity'] # Recording the restaurant and address into a hash
          end
        else
          @restaurants = [] # Just in case the API stops working
          @error = response['error_message']
        end
    end
  end

end

app/views/chats/match.html.erb
<h2>Make A Date</h2>

<% count = 0 %>

<% @restaurants.each do |x, y| %>

  <% if count % 3 == 0 %>
    <h2><%= @suggestions.shift %></h2>
  <% end %>
  <% count += 1 %>

  <div class='box'>
    <%= x %><br>
    <%= y %>
    <iframe
      width="250"
      height="225"
      frameborder="0" style="border:0"
      src="<%= "https://www.google.com/maps/embed/v1/search?key=AIzaSyDzMn29qnBUFN4FUuepeyzhSbQo1J9lkvo&q=" + x.gsub(" ", "+").gsub("&", "") %>">
    </iframe>
  </div>
<% end %>
<!-- <%= @error if @error.present? %> -->

app/views/chats/show.html.erb
<h2>Chat with <%= @user1.firstname %> and <%= @user2.firstname %></h2>
<div class='match'><%= link_to('Make A Date', match_path ) %></div>

<div class='chat'>
  <table>
  <% @messages.each do |msg| %>
    <tr>
      <td><%= msg.created_at.strftime("%r") %></td>
      <td><%= image_tag(msg.user.image, :class => 'px48') %></td>
      <td><%= msg.user.firstname %>: </td>
      <td><%= msg.message %></td>
  <% end %>
  </table>

  <form action="/chats/<%=@chat.id%>" method="post">
    <label for="message"></label>
    <textarea type="text" rows="3" cols='50' id="message" name="message" placeholder="Post..."></textarea>

    <button>Send</button>
  </form>
</div>